name:                gamejam
version:             0.1.0.0
github:              "erratic-c-programmer/gamejam"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2022 Author name here"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/haskell-sdl-test#readme>

dependencies:
- base >= 4.7 && < 5
- bmp >= 1.2 && < 1.3
- lens >= 5 && < 6
- mtl >= 2.2 && < 3
- random >= 1.2 && < 2
- sdl2 >= 2.5 && < 2.6
- strict >= 0.2 && < 1
- text >= 1.2 && < 2
- vector >= 0.12 && < 1

library:
  source-dirs: src

executables:
  gamejam-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -O2
    dependencies:
    - gamejam

tests:
  gamejam-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - gamejam
